#!/bin/bash

source github.env
sed -e "s/var.aws_region/\"$AWS_REGION\"/" -e "s/var.bucket/\"terraform-$AWS_ACCOUNT-$AWS_REGION-an\"/" scripts/terraform.tf > applications/$STACK_SET/generated_terraform.tf
cd applications/$STACK_SET
terraform init -backend-config="key=$STACK_SET/terraform.tfstate" -reconfigure
terraform apply -auto-approve
