#!/bin/bash

source github.env
sed "s/var.aws_region/\"$AWS_REGION\"/" scripts/terraform.tf > $CURRENT_STACK/destroy.tf
cd $CURRENT_STACK
terraform init -backend-config="key=$AWS_ACCOUNT/$CURRENT_STACK/$AWS_REGION/terraform.tfstate" -reconfigure
terraform plan
