name: Merge to Main branch

on:
  push:
    branches:
    - main

permissions:
  id-token: write # Required for OIDC
  contents: read

env:
  TF_LOG: INFO
  TF_INPUT: false

jobs: 
  merge-pull-request:
    runs-on: ubuntu-latest
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    # Set the working directory to vnet for the config files
    defaults:
        run:
          shell: bash
          working-directory: .

    steps:
      - run: echo "Triggered by a ${{ github.event_name }} event on branch ${{ github.ref }} by ${{ github.actor }}, testing target ${{ vars.TESTING_TARGET }}"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::821080507765:role/github-actions-user-github-actions-role
          aws-region: us-east-2
      - name: Check out repository code
        uses: actions/checkout@v5
      # Install the selected version of Terraform CLI 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.6"
      - name: Terraform Version
        run: terraform version
      - name: Terraform Init
        id: init
        env:
          # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # AWS_REGION: "us-east-2"
          BUCKET_NAME: "benj58xu-terraform-backend"
          KEY_NAME: "terraform.tfstate"
        run: terraform init 
 
      # On merge to main apply changes
      - name: Terraform Apply
        id: apply
        env:
          # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # AWS_REGION: "us-east-2"
          BUCKET_NAME: "benj58xu-terraform-backend"
          KEY_NAME: "terraform.tfstate"
        run: terraform apply -auto-approve
      - name: List files
        run: ls ${{ github.workspace }}
