name: Run Terraform Plan on Pull Request

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write # Required for OIDC
  contents: read

env:
  TF_LOG: INFO
  TF_INPUT: false

jobs: 
  create-pull-request:
    name: Run Terraform Plan
    runs-on: ubuntu-latest
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
        run:
          shell: bash
          working-directory: .

    steps:
      - run: echo "Triggered by a ${{ github.event_name }} event on branch ${{ github.ref }} by ${{ github.actor }}, testing target ${{ vars.TESTING_TARGET }}"
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: cat github.env >> $GITHUB_ENV
      - run: sed -e "s/var.aws_region/\"$AWS_REGION\"/" -e "s/var.bucket/\"terraform-$AWS_ACCOUNT-$AWS_REGION-an\"/" scripts/terraform.tf > applications/$STACK_SET/terraform.tf
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/github-actions-user-github-actions-role
          aws-region: us-east-2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.7"
      - name: Terraform Init
        id: init
        run: terraform init -backend-config="key=$STACK_SET/terraform.tfstate"
        working-directory: applications/${{ env.STACK_SET }}
      - name: Terraform Plan
        id: plan
        run: |
          if [ "$DESTROY" == "true" ]; then
            terraform plan -no-color -destroy
          else
            terraform plan -no-color
          fi
        working-directory: applications/${{ env.STACK_SET }}
      - name: Add Plan Comment
        id: comment
        uses: actions/github-script@v6
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.BEN_GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
        
            Show Plan
            
            \`\`\`${process.env.PLAN}\`\`\`
            
            
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
              
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });