name: Pull Request Main

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write # Required for OIDC
  contents: read

env:
  TF_LOG: INFO
  TF_INPUT: false

jobs: 
  create-pull-request:
    runs-on: ubuntu-latest
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    # Set the working directory to vnet for the config files
    defaults:
        run:
          shell: bash
          working-directory: .

    steps:
      - run: echo "Triggered by a ${{ github.event_name }} event on branch ${{ github.ref }} by ${{ github.actor }}, testing target ${{ vars.TESTING_TARGET }}"
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: cat github.env >> $GITHUB_ENV
      - run: sed "s/var.aws_region/\"$AWS_REGION\"/" scripts/terraform.tf > applications/$STACK_SET/terraform.tf
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/github-actions-user-github-actions-role
          aws-region: us-east-2
      # Install the selected version of Terraform CLI 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.7"
      - name: Terraform Init
        id: init
        # env:
          # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init -backend-config="key=$STACK_SET/$AWS_ACCOUNT/$AWS_REGION/terraform.tfstate"
        working-directory: applications/${{ env.STACK_SET }}
      # Run Terraform Plan to check for any changes that would be applied
      - name: Terraform Plan
        id: plan
        env:
          # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # AWS_REGION: "us-east-2"
          BUCKET_NAME: "benj58xu-terraform-backend"
          KEY_NAME: "terraform.tfstate"
        run: terraform plan -no-color
        working-directory: applications/${{ env.STACK_SET }}
      # Add a comment to pull requests with plan results
      - name: Add Plan Comment
        id: comment
        uses: actions/github-script@v6
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.BEN_GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
        
            Show Plan
            
            \`\`\`${process.env.PLAN}\`\`\`
            
            
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
              
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });