name: Push to feature branch

on:
  push:
    branches:
      - 'develop'

permissions:
  id-token: write # Required for OIDC
  contents: read

env:
  TF_LOG: INFO
  TF_INPUT: false

jobs: 
  push-to-feature-branch:
    runs-on: ubuntu-latest
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    # Set the working directory to vnet for the config files
    defaults:
        run:
          shell: bash
          working-directory: .

    steps:
      - run: echo "Triggered by a ${{ github.event_name }} event on branch ${{ github.ref }} by ${{ github.actor }}, testing target ${{ vars.TESTING_TARGET }}"
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: cat github.env >> $GITHUB_ENV
      - run: sed "s/var.aws_region/\"$AWS_REGION\"/" terraform.tf > $CURRENT_STACK/terraform.tf
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/github-actions-user-github-actions-role
          aws-region: us-east-2
      - name: List environment variables
        run: env
      - name: List files
        run: ls ${{ github.workspace }}
      # Install the selected version of Terraform CLI 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.7"
      - name: Terraform Version
        run: terraform version
      - name: Terraform Init
        id: init
        env:
          # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          NOT_NEEDED: "$AWS_ACCOUNT/$CURRENT_STACK/$AWS_REGION/terraform.tfstate"
        run: terraform init -backend-config="key=$AWS_ACCOUNT/$CURRENT_STACK/$AWS_REGION/terraform.tfstate" -var="aws_region=$AWS_REGION"
        working-directory: ${{ env.CURRENT_STACK }}
      # Run a terraform fmt to check syntax
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
      # Run a terraform validate
      - name: Terraform Validate
        id: validate
        # Run even if formatting fails
        if: success() || failure()
        env:
          # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          NOT_NEEDED: "$AWS_ACCOUNT/$CURRENT_STACK/$AWS_REGION/terraform.tfstate"
        run: terraform validate -no-color -backend-config="key=$AWS_ACCOUNT/$CURRENT_STACK/$AWS_REGION/terraform.tfstate" -var="aws_region=$AWS_REGION"
        working-directory: ${{ env.CURRENT_STACK }}

